#!/bin/bash

paperdir="$HOME/Documents/Papers"
mapfile -t papers < <(find "$paperdir" -name '*.pdf' -exec basename {} \;)

IFS=$'\n' paper=$(echo "${papers[*]}" | dmenu -i -p 'Paper:')

paper=$(find "$paperdir" -name "$paper")

if [ -n "$paper" ]; then
    exec zathura "$paper"
fi
