#!/bin/bash

declare -A config=(
    [alacritty]="$HOME"/.config/alacritty
    [zsh]="$HOME"/.config/zsh/.zshrc
    [vim]="$HOME"/.config/nvim/init.vim
    [xmonad]="$HOME"/.xmonad/xmonad.hs
    [vifm]="$HOME"/.config/vifm/vifmrc
)

mapfile -t scripts < <(find "$HOME"/.local/bin -not -name 'dmenu*' -type f)

for file in "${scripts[@]}"; do
    if rg -q '^#!/bin/' "$file"; then
        config[$(basename "$file")]="$file"
    fi
done

IFS=$'\n' key="$(echo "${!config[*]}" | dmenu -p 'Config:')"

if [ -n "$key" ]; then
    alacritty -e nvim "${config[$key]}"
else
    exit
fi

response="$(echo $'yes\nno' | dmenu -p 'Commit?')"

args=("--git-dir=${HOME}/.config/dotfiles/" "--work-tree=${HOME}")

if [ "$response" = yes ]; then
    if git "${args[@]}" add "${config[$key]}"; then
        alacritty -e git "${args[@]}" commit
        git "${args[@]}" push -u origin master
    fi
fi
