#!/bin/bash

manual="$(man -k . | awk '{print $1 " " $2}' | dmenu -p 'Man:')"

a="${manual% *}"
b="${manual#*(}"
b="${b%)*}"

if [ -n "$a" ] && [ -n "$b" ]; then
    exec alacritty -e man "$b" "$a"
fi
